name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # Install project dependencies from requirements.txt
        # This is needed so pylint can find and verify your project's imports
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Set PYTHONPATH for internal imports
      run: |
        # This tells Python/Pylint to look for modules in the current directory ('.')
        # Fixes 'Unable to import "models"' or 'Unable to import "app"'
        echo "PYTHONPATH=." >> $GITHUB_ENV
        
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')